name: Build SFA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAGS: with_quic,with_grpc,with_wireguard,with_gvisor,with_shadowsocksr,with_utls,with_clash_api,with_proxyprovider

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest go version
        id: go_version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.version.outputs.go_version }}

      - name: Checkout Source Code
        run: |
          git clone -b dev-next-yaott https://github.com/CHIZI-0618/sing-box code
          cd code
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote add PuerNya https://github.com/PuerNya/sing-box
          git fetch PuerNya building
          git cherry-pick -x -n $(git log PuerNya/building --grep=keep-ssr --format=format:"%H")
          git cherry-pick -x -n $(git log PuerNya/building --grep=bittorrent --format=format:"%H")
          #git revert b728ba5
          cd ..
          #mv ${{ github.workspace }}/code/* ${{ github.workspace }} && rm -rf ${{ github.workspace }}/code
          git clone -b build https://github.com/yaotthaha/sing-box-for-android SFA
          cd SFA
          git remote add snsfa https://github.com/SagerNet/sing-box-for-android
          git fetch snsfa main
          git merge snsfa/main
          cd ..

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 20

      - name: Prepare
        run: |
          tag="${{ github.event.inputs.version_name }}-${{ github.event.inputs.version_code }}-$(date +%Y%m%d%H%M)"
          echo "RELEASE_NAME=Released on ${tag}" >> $GITHUB_ENV
          echo "TAG_NAME=${tag}" >> $GITHUB_ENV
          cd code
          echo "VERSION_NAME=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)" >> $GITHUB_ENV
          echo "VERSION_CODE=$(date +%Y%m%d%H)" >> $GITHUB_ENV
          cd ..

      
      - name: Build SFA
        env:
          KEYSTORE_PATH: "${{ github.workspace }}/.github/k.jks"
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
          VERSION_CODE: ${{ github.event.inputs.version_code }}
          VERSION_NAME: ${{ github.event.inputs.version_name }}
        run: |
          mkdir -p SFA/app/libs/
          cd code
          make lib_install
          CGO_ENABLED=1 gomobile bind -v -androidapi 21 -javapkg=io.nekohasekai -libname=box -tags ${TAGS} -ldflags "-X github.com/sagernet/sing-box/constant.Version=${version} -buildid=" ./experimental/libbox
          cp ./libbox.aar ${{ github.workspace }}/SFA/app/libs/
          cd ../SFA
          #sed -i '23s|.*|        versionCode getProps("VERSION_CODE").toInteger()|' ${{ github.workspace }}/SFA/app/build.gradle
          #sed -i '24s|.*|        versionName getProps("VERSION_NAME")|' ${{ github.workspace }}/SFA/app/build.gradle
          #sed -i '30s|.*|            storeFile file(System.getenv("KEYSTORE_PATH"))|' ${{ github.workspace }}/SFA/app/build.gradle
          sed -i '0,/storeFile file("android.jks")/s/storeFile file("android.jks")/storeFile file(System.getenv("KEYSTORE_PATH"))/1' ${{ github.workspace }}/SFA/app/build.gradle
          #sed -i '/fun updateGroups(groups: List<OutboundGroup>) {}/a\        fun clearLog() {}' ${{ github.workspace }}/SFA/app/src/main/java/io/nekohasekai/sfa/utils/CommandClient.kt
          #sed -i '0,/handler.updateGroups(groups)/s/handler.updateGroups(groups)/handler.updateGroups(groups)\n        }\n\n        override fun clearLog() {\n           handler.clearLog()/1' ${{ github.workspace }}/SFA/app/src/main/java/io/nekohasekai/sfa/utils/CommandClient.kt
          #chmod +x ./gradlew
          #dos2unix ./gradlew
          chmod 0755 ./gradlew
          ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SFA
          path: ${{ github.workspace }}/SFA/app/build/outputs/apk/

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.TAG_NAME }}
          body: ${{ env.RELEASE_NAME }}
          file_glob: true
          file: |
           ${{ github.workspace }}/SFA/app/build/outputs/apk/*.apk
